name       : compiz
version    : 0.9.13.1
release    : 6
source     :
    - https://launchpad.net/compiz/0.9.13/0.9.13.1/+download/compiz-0.9.13.1.tar.bz2 : 9854802ba2a072a497552a55cc03cce1e947ff68ed3755b484c218f688222cbf
license    :
    - GPL-2.0
    - LGPL-2.1+
    - MIT
component  : desktop.mate
summary    : Composite manager for Aiglx and Xgl, with plugins and CCSM.
description: |
    Composite manager for Aiglx and Xgl, with plugins and CCSM.
libsplit   : no
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-1)
    - pkgconfig(fuse)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(glu)
    - pkgconfig(libmetacity)
    - pkgconfig(libnotify)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(protobuf)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - desktop-file-utils
    - libboost-devel
    - libjpeg-turbo-devel
    - pyrex
rundeps    :
    - python-gtk2
    - xprop
setup      : |
    mkdir build && pushd build
    %cmake .. -DCOMPIZ_BUILD_WITH_RPATH=FALSE -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCOMPIZ_PACKAGING_ENABLED=TRUE \
              -DCOMPIZ_DISABLE_GS_SCHEMAS_INSTALL=OFF -DCOMPIZ_DISABLE_PLUGIN_KDE=ON -DCOMPIZ_BUILD_TESTING=OFF \
              -DUSE_KDE4=OFF -DBUILD_GLES=OFF -DBUILD_XORG_GTEST=OFF  -DCOMPIZ_DEFAULT_PLUGINS="composite,opengl,decor,resize,place,move,compiztoolbox,staticswitcher,regex,animation,wall,ccp" \
              -DCMAKE_C_FLAGS="$CFLAGS -lutil" \
              -DCMAKE_CXX_FLAGS="$CXXFLAGS -lutil"
build      : |
    unset LD_AS_NEEDED
    pushd build
    %make
install    : |
    pushd build
    %make_install

