name       : compiz
version    : 0.8.18
release    : 28
source     :
    - https://gitlab.com/compiz/compiz-core/-/archive/v0.8.18/compiz-core-v0.8.18.tar.bz2 : e87018b2d6c9ab3da87d910b117a7ae35f64328eea485e6c2a532501b361144c
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.mate
summary    : Compiz is an OpenGL compositing manager
description: |
    Compiz is an OpenGL compositing manager that uses GLX_EXT_texture_from_pixmap for binding redirected top-level windows to texture objects. It has a flexible plug-in system and it is designed to run well on most graphics hardware.
libsplit   : no
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-1)
    - pkgconfig(fuse)
    - pkgconfig(glu)
    - pkgconfig(libmarco-private)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(sm)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
    - desktop-file-utils
    - intltool
rundeps    :
    - xprop
environment: |
    unset LD_AS_NEEDED
setup      : |
    sed -i -e "s|librsvg-features.h|rsvg-features.h|g" plugins/svg.c
    %autogen --disable-rpath --disable-static
build      : |
    %make
install    : |
    %make_install
